# This is a basic workflow to help you get started with Actions

name: react_practice
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Nodejs
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 12
    - name: Install yarn
      uses: Borales/actions-yarn@v2.3.0
      with:
        cmd: install
    - name: yarn build
      run: yarn build
    - name: Install surge
      run: npm install -g surge
    - name: deploy surge
      run: surge ./build react_practice1.surge.sh --token ${{secrets.SURGE_TOKEN}} 
       
